### ISSUE TITLE
Have the ability to define a "description" for an article

### ISSUE THREAD

**Issue by mansona** [ember-learn/ember-ghost-ember-template#4]
We are currently using the `{{excerpt}}` helper to take the first 40 words to use as an "intro" on the index page. 

We should be able to specify the description/intro in post yaml and if it is not present it should fallback to using `{{excerpt}}``

note: this needs to work with SEO description in ember-ghost too 👍

**Comment by amyrlam** [comment]
Solved by https://github.com/ember-learn/ember-ghost-ember-template/commit/005d93d933cc4c4c56d13210b5c3e0a12309a4d1
